package com.nailorsh.repeton.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)
val ScreenBackground = Color(0xFFEFEFEF)
val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)
val SpotColor = Color(0x40000000)
val AmbientColor = Color(0x40000000)
val White = Color(0xFFFFFFFF)
val Black = Color(0xFF000000)
val SelectedDayColor = Color(android.graphics.Color.parseColor("#FFAE74"))
val AddLessonButtonColor = Color(android.graphics.Color.parseColor("#4B9E58"))
val LineColor = Color(android.graphics.Color.parseColor("#BAB3B3"))
val StarColor = Color(0xFFFFA800)
val WriteButtonBackgroundColor = Color(0xFF3856BF)
val WriteButtonTextColor = White
val TitleColor = Black
val BodyColor = Black
val ShowMoreTextButtonColor = Color(0xFF3D3D3D)
val TextFieldTextColor = Black
val SearchPlaceholderColor = Color(0xFF3D3D3D)
val HomeWorkButtonColor = Color(0xFF3A65FF)
val SubjectColor = Color(0xFF3A65FF)
val BottomNavigationBarColor = Color(0xFFF6F6F6)
val SelectedBottomBarIconColor = Color(0xFF3856BF)
val UnselectedBottomBarIconColor = Black



val md_theme_light_primary = Color(0xFF006A67)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF70F7F1)
val md_theme_light_onPrimaryContainer = Color(0xFF00201F)
val md_theme_light_secondary = Color(0xFF0061A6)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD2E4FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001C37)
val md_theme_light_tertiary = Color(0xFF49607B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD1E4FF)
val md_theme_light_onTertiaryContainer = Color(0xFF021D35)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFB)
val md_theme_light_onBackground = Color(0xFF191C1C)
val md_theme_light_surface = Color(0xFFFAFDFB)
val md_theme_light_onSurface = Color(0xFF191C1C)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E3)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4948)
val md_theme_light_outline = Color(0xFF6F7978)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F0)
val md_theme_light_inverseSurface = Color(0xFF2D3131)
val md_theme_light_inversePrimary = Color(0xFF4EDAD5)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006A67)
val md_theme_light_outlineVariant = Color(0xFFBEC9C7)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF4EDAD5)
val md_theme_dark_onPrimary = Color(0xFF003735)
val md_theme_dark_primaryContainer = Color(0xFF00504D)
val md_theme_dark_onPrimaryContainer = Color(0xFF70F7F1)
val md_theme_dark_secondary = Color(0xFFA0CAFF)
val md_theme_dark_onSecondary = Color(0xFF003259)
val md_theme_dark_secondaryContainer = Color(0xFF00497E)
val md_theme_dark_onSecondaryContainer = Color(0xFFD2E4FF)
val md_theme_dark_tertiary = Color(0xFFB1C8E8)
val md_theme_dark_onTertiary = Color(0xFF1A324B)
val md_theme_dark_tertiaryContainer = Color(0xFF324862)
val md_theme_dark_onTertiaryContainer = Color(0xFFD1E4FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1C)
val md_theme_dark_onBackground = Color(0xFFE0E3E2)
val md_theme_dark_surface = Color(0xFF191C1C)
val md_theme_dark_onSurface = Color(0xFFE0E3E2)
val md_theme_dark_surfaceVariant = Color(0xFF3F4948)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C7)
val md_theme_dark_outline = Color(0xFF889392)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1C)
val md_theme_dark_inverseSurface = Color(0xFFE0E3E2)
val md_theme_dark_inversePrimary = Color(0xFF006A67)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF4EDAD5)
val md_theme_dark_outlineVariant = Color(0xFF3F4948)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF009692)
